package com.fitscan.app.domain.usecase

import android.content.Context
import android.graphics.Bitmap
import com.fitscan.app.data.remote.RetrofitClient
import com.fitscan.app.data.repository.MeasurementRepository
import com.fitscan.app.domain.model.BodyMeasurements
import com.fitscan.app.domain.model.ClothingSize
import com.fitscan.app.domain.model.ScanResult
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.MultipartBody
import okhttp3.RequestBody.Companion.asRequestBody
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.File
import java.io.FileOutputStream

class AnalyzeImageUseCase(
    private val context: Context,
    private val repository: MeasurementRepository
) {
    suspend operator fun invoke(bitmap: Bitmap, heightCm: Float): Result<ScanResult> = withContext(Dispatchers.IO) {
        try {
            // 1. Convert the captured Bitmap into a temporary JPEG file for uploading
            val tempFile = File(context.cacheDir, "upload_frame_${System.currentTimeMillis()}.jpg")
            val outputStream = FileOutputStream(tempFile)
            bitmap.compress(Bitmap.CompressFormat.JPEG, 90, outputStream)
            outputStream.flush()
            outputStream.close()

            // 2. Package the file and height into the Multipart Format the Python backend expects
            val requestFile = tempFile.asRequestBody("image/jpeg".toMediaTypeOrNull())
            val imagePart = MultipartBody.Part.createFormData("image_file", tempFile.name, requestFile)
            val heightPart = heightCm.toString().toRequestBody("text/plain".toMediaTypeOrNull())

            // 3. FIRE THE NETWORK REQUEST TO FASTAPI!
            val response = RetrofitClient.api.analyzeImage(imagePart, heightPart)

            // 4. Handle the Server Response
            if (response.isSuccessful && response.body() != null) {
                val apiData = response.body()!!

                // Clean up the temporary file so we don't leak storage
                tempFile.delete()

                // Map the JSON response from Python into your Android Kotlin Domain Model
                val result = ScanResult(
                    id = 0, // Auto-generated by Room Database
                    timestamp = System.currentTimeMillis(),
                    confidenceScore = 95, // Baseline network confidence
                    heightCm = heightCm,
                    recommendedSize = "Calculated", // Placeholder for SizeMapper UI
                    measurements = BodyMeasurements(
                        heightCm = heightCm,
                        shoulderWidth = apiData.shoulderWidth,
                        chestCirc = apiData.chestCircumference,
                        waistCirc = apiData.waistCircumference,
                        hipWidth = apiData.hipWidth,
                        hipCirc = apiData.hipCircumference,
                        armLength = apiData.armLength
                    ),
                    clothingSizes = listOf(
                        ClothingSize(
                            category = "Tops",
                            sizeText = "TBD",
                            euSize = "TBD",
                            usSize = "TBD",
                            ukSize = "TBD",
                            fitNotes = "Calibrated via: ${apiData.calibrationMethod}"
                        )
                    )
                )

                // 5. Save the successful network calculation to the local Room Database
                repository.saveScan(result)

                Result.success(result)
            } else {
                tempFile.delete()
                val errorBody = response.errorBody()?.string() ?: "Unknown Server Error"
                Result.failure(Exception("API Error ${response.code()}: $errorBody"))
            }

        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}